name: lead_adminpanelone
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1




  #---------------- Packages start ------------#


dependencies:
  flutter:
    sdk: flutter


  #Icons
  cupertino_icons: ^1.0.8

  # Extra usage packages
  google_fonts: ^6.3.1
  url_strategy: ^0.3.0
  go_router: ^16.2.4
  flutter_admin_scaffold: ^1.4.0
  data_table_2: ^2.6.0
  #state management#
  get: ^4.7.2


  #------- packages end ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true


  # ---------- Local Assets --------- #
  assets:
    - assets/logo/
    - assets/icons/
    - assets/Images/

